import type { TokenBundle, ThemedLeaf, DtcgLeaf, TypographyRole, VerticalLeaf } from './types.ts';

function themedMap<T extends ThemedLeaf>(
  entries: Record<string, T>,
): { light: Record<string, string>; dark: Record<string, string> } {
  const light: Record<string, string> = {};
  const dark: Record<string, string> = {};
  for (const [key, leaf] of Object.entries(entries)) {
    light[key] = leaf.light.$value.toString();
    dark[key] = leaf.dark.$value.toString();
  }
  return { light, dark };
}

function plainMap(entries: Record<string, DtcgLeaf>): Record<string, string | number> {
  const out: Record<string, string | number> = {};
  for (const [key, leaf] of Object.entries(entries)) {
    if (key.startsWith('$')) continue;
    out[key] = leaf.$value;
  }
  return out;
}

function roleMap(entries: Record<string, TypographyRole>): Record<string, TypographyRole> {
  const out: Record<string, TypographyRole> = {};
  for (const [key, value] of Object.entries(entries)) {
    if (key.startsWith('$')) continue;
    out[key] = value;
  }
  return out;
}

function verticalMap(
  entries: Record<string, VerticalLeaf>,
): Record<string, { value: string; tint: string | null }> {
  const out: Record<string, { value: string; tint: string | null }> = {};
  for (const [key, leaf] of Object.entries(entries)) {
    out[key] = {
      value: leaf.$value ?? '',
      tint: leaf.bgTint ?? null,
    };
  }
  return out;
}

export function emitTypescript(tokens: TokenBundle): string {
  const shape = {
    color: {
      brand: themedMap(tokens.color.color.brand),
      surface: themedMap(tokens.color.color.surface),
      border: themedMap(tokens.color.color.border),
      text: themedMap(tokens.color.color.text),
      status: themedMap(tokens.color.color.status),
      vertical: verticalMap(tokens.color.color.vertical),
    },
    shadow: themedMap(tokens.shadow.shadow),
    typography: {
      family: plainMap(tokens.typography.typography.font.family),
      weight: plainMap(tokens.typography.typography.font.weight),
      size: plainMap(tokens.typography.typography.font.size),
      tracking: plainMap(tokens.typography.typography.font.tracking),
      leading: plainMap(tokens.typography.typography.font.leading),
      role: roleMap(tokens.typography.typography.role),
    },
    spacing: plainMap(tokens.spacing.space),
    radius: plainMap(tokens.radius.radius),
    motion: {
      duration: plainMap(tokens.motion.motion.duration),
      easing: plainMap(tokens.motion.motion.easing),
      lift: plainMap(tokens.motion.motion.lift),
    },
    zIndex: plainMap(tokens.motion.zIndex),
    opacity: plainMap(tokens.opacity.opacity),
  };

  const body = JSON.stringify(shape, null, 2);

  return [
    '/* eslint-disable */',
    '// AUTO-GENERATED by @app/design-tokens — do not edit by hand.',
    '// Source: docs/design/shared/tokens.json',
    '// Rebuild: pnpm design:build',
    '',
    `export const designTokens = ${body} as const;`,
    '',
    'export type DesignTokens = typeof designTokens;',
    '',
  ].join('\n');
}
