// Shape of the slices `loadTokens()` carves out of docs/design/shared/tokens.json.
// Kept permissive — the emitters know how to navigate it.

export interface DtcgLeaf {
  $value: string | number;
  $type?: string;
  $description?: string;
}

export interface ThemedLeaf {
  light: DtcgLeaf;
  dark: DtcgLeaf;
  sepia?: DtcgLeaf;
  forest?: DtcgLeaf;
}

export type ColorValue = ThemedLeaf | DtcgLeaf;

export interface ColorFile {
  description?: string;
  color: {
    brand: Record<string, ThemedLeaf>;
    surface: Record<string, ThemedLeaf>;
    border: Record<string, ThemedLeaf>;
    text: Record<string, ThemedLeaf>;
    status: Record<string, ThemedLeaf>;
    vertical: Record<string, VerticalLeaf>;
  };
}

export interface VerticalLeaf {
  $value?: string;
  $type?: string;
  bgTint?: string;
  $description?: string;
}

export interface TypographyFile {
  typography: {
    font: {
      family: Record<string, DtcgLeaf>;
      weight: Record<string, DtcgLeaf>;
      size: Record<string, DtcgLeaf>;
      tracking: Record<string, DtcgLeaf>;
      leading: Record<string, DtcgLeaf>;
    };
    role: Record<string, TypographyRole>;
  };
}

export interface TypographyRole {
  size: string;
  weight: string;
  tracking: string;
  leading: string;
  mono?: boolean;
}

export interface SpacingFile {
  space: Record<string, DtcgLeaf>;
}

export interface RadiusFile {
  radius: Record<string, DtcgLeaf>;
}

export interface ShadowFile {
  shadow: Record<string, ThemedLeaf>;
}

export interface MotionFile {
  motion: {
    duration: Record<string, DtcgLeaf>;
    easing: Record<string, DtcgLeaf>;
    lift: Record<string, DtcgLeaf>;
  };
  zIndex: Record<string, DtcgLeaf>;
}

export interface OpacityFile {
  description?: string;
  opacity: Record<string, DtcgLeaf>;
}

// Media-surface colours. Unlike `ColorFile`, these are NOT themed: video is dark
// under every theme, so on-media white must stay white in light mode too. Emitted
// once under `:root` alongside motion/space/zIndex/opacity — never per theme.
// The group carries a `$description` key, so emitters must skip `$`-prefixed keys.
export interface MediaFile {
  media: Record<string, DtcgLeaf>;
}

export interface TokenBundle {
  color: ColorFile;
  typography: TypographyFile;
  spacing: SpacingFile;
  radius: RadiusFile;
  shadow: ShadowFile;
  motion: MotionFile;
  opacity: OpacityFile;
  media: MediaFile;
}

export const BANNER = [
  '/* ==============================================================',
  '   AUTO-GENERATED by @app/design-tokens — do not edit by hand.',
  '   Source: docs/design/shared/tokens.json',
  '   Rebuild: pnpm design:build',
  '   ============================================================== */',
].join('\n');

export const DART_BANNER = [
  '// ==============================================================',
  '// AUTO-GENERATED by @app/design-tokens — do not edit by hand.',
  '// Source: docs/design/shared/tokens.json',
  '// Rebuild: pnpm design:build',
  '// ==============================================================',
].join('\n');
