/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/access/grants': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List a user's access grants
     * @description Returns every grant issued to the given user, both library- and course-scoped.
     */
    get: operations['listGrantsByUser'];
    put?: never;
    /**
     * Grant a user READ access to a library or course
     * @description Idempotent on (userId, target). Returns 409 if the same grant already
     *     exists. Only admins (`session.user.role === 'admin'`) may call this;
     *     other authenticated users get 403.
     */
    post: operations['registerGrant'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/access/grants/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Revoke an access grant
     * @description Permanently removes the grant identified by `id`. The affected user immediately loses the access level the grant provided.
     */
    delete: operations['revokeGrant'];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/courses': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List courses (optionally filtered by library)
     * @description Returns courses the requester can see. Non-admins see only courses inside
     *     libraries they have a READ AccessGrant for; admins see all.
     */
    get: operations['listCourses'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/courses/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get a single course
     * @description Returns the full CourseDto for one course by its server-generated cuid. Non-admins must hold a READ AccessGrant on the course's library.
     */
    get: operations['getCourse'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Update course metadata
     * @description Admin-only. Updates any combination of title / description / slug.
     *     Slug must be unique within the same library.
     *     At least one of `title`, `description`, or `slug` must be present
     *     (server-side validation rule — OpenAPI cannot express "at-least-one" natively).
     */
    patch: operations['updateCourse'];
    trace?: never;
  };
  '/api/v1/home/continue-watching': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List courses the requester is in the middle of
     * @description Returns the requester's courses ordered by recency (most-recently-watched
     *     first), capped by `limit`. Reads from a denormalised
     *     `CourseProgressReadModel` projection that's updated by `LessonCompleted`
     *     and `LessonProgressRecorded` events. Empty array for new users.
     */
    get: operations['getContinueWatching'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/lessons/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get a lesson with its materials and subtitles
     * @description Returns lesson metadata, sidecar materials (PDF / Markdown / text / image),
     *     and available subtitle tracks. Raw filesystem paths are intentionally absent
     *     from the response (NFR-S-01); the player obtains a signed stream token for
     *     the lesson video and the material/subtitle blobs separately.
     */
    get: operations['getLesson'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/lessons/{id}/stream-url': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Mint a short-lived signed URL for a lesson video
     * @description Returns a URL pointing at `/api/v1/stream/lessons/{id}` with a signed
     *     query-param token bound to `(userId, lessonId, expiresAt)`. The token
     *     is HMAC-signed; the streaming endpoint verifies it without a database
     *     lookup. Default TTL is 15 minutes (configurable server-side). Clients
     *     must request a fresh URL when the previous one expires — refresh policy
     *     is up to the player.
     */
    get: operations['issueStreamUrl'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/libraries': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List all registered libraries
     * @description Returns all libraries the requester has READ access to. Admins see
     *     everything.
     */
    get: operations['listLibraries'];
    put?: never;
    /**
     * Register a new library
     * @description Persists a new library pointing at an absolute filesystem path.
     *     Idempotent on rootPath: a 409 is returned if a library with the same
     *     rootPath already exists.
     */
    post: operations['registerLibrary'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/libraries/{id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get a library by id
     * @description Returns a single library by its server-generated identifier.
     */
    get: operations['getLibrary'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/libraries/{id}/scans': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Trigger a scan of a library
     * @description Walks the library tree, recognises Course / Section / Lesson layout,
     *     and records discoveries on a Scan aggregate. Returns 202 immediately
     *     with `status: running`; clients poll
     *     `GET /libraries/{id}/scans/latest`. A second scan with no filesystem
     *     changes is observably a no-op (`filesAdded` and `filesUpdated` are
     *     zero).
     */
    post: operations['runLibraryScan'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/libraries/{id}/scans/latest': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get the most recent scan for a library
     * @description Returns the latest scan record regardless of status (running, succeeded, failed, cancelled).
     */
    get: operations['getLatestLibraryScan'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Service health probe
     * @description Reports combined health status of the service and its runtime
     *     dependencies (database, cache, realtime bus).
     */
    get: operations['getHealth'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/progress': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Record (upsert) the requester's progress on a lesson
     * @description Last-write-wins on `clientUpdatedAt`: out-of-order writes (older
     *     timestamp than the current state) are silently accepted with the prior
     *     state echoed back. The first write that crosses 90 % completion sets
     *     `completed: true` and stamps `completedAt`; subsequent writes do not
     *     re-emit completion. Always returns the post-merge state — clients can
     *     use it to detect whether their write was the one that bumped the counter.
     */
    post: operations['recordLessonProgress'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/progress/{lessonId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get the requester's progress on a lesson
     * @description Returns the current progress record for the requesting user on the
     *     given lesson. 403 is returned both when the requester has no READ grant
     *     covering the lesson **and** when the lesson does not exist — preventing
     *     existence leakage. 404 is returned only when the lesson exists but the
     *     requester has not yet recorded any progress.
     */
    get: operations['getLessonProgress'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/realtime/token': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Issue a short-lived Centrifugo connection token
     * @description Mints a short-lived HMAC-signed JWT that the client can use to connect
     *     to Centrifugo. Requires an active Better Auth session (cookie on web,
     *     bearer token on mobile).
     */
    post: operations['issueRealtimeToken'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * LibraryTarget
     * @example {
     *       "kind": "library",
     *       "libraryId": "clxvp1234567890abcdefghij"
     *     }
     */
    0: {
      /**
       * @description Discriminator value indicating a library-scoped grant. (enum property replaced by openapi-typescript)
       * @enum {string}
       */
      kind: 'library';
      /** @description Server-generated cuid of the target library. */
      libraryId: string;
    };
    /**
     * CourseTarget
     * @example {
     *       "kind": "course",
     *       "courseId": "clxvcrs0000000000000000001"
     *     }
     */
    1: {
      /**
       * @description Discriminator value indicating a course-scoped grant. Accepted in v1 even though the Course aggregate (E06-F03-S01) has not landed yet — keeps the contract stable for E14-F04-S01. (enum property replaced by openapi-typescript)
       * @enum {string}
       */
      kind: 'course';
      /** @description Server-generated cuid of the target course (e.g. "DDD by Eric Evans"). */
      courseId: string;
    };
    /**
     * @description A single access grant issued by an admin.
     * @example {
     *       "id": "clxvgnt0000000000000000001",
     *       "userId": "clxvusr0000000000000000001",
     *       "target": {
     *         "kind": "library",
     *         "libraryId": "clxvp1234567890abcdefghij"
     *       },
     *       "level": "READ",
     *       "createdAt": "2026-04-25T10:00:00Z"
     *     }
     * @example {
     *       "id": "clxvgnt0000000000000000002",
     *       "userId": "clxvusr0000000000000000001",
     *       "target": {
     *         "kind": "course",
     *         "courseId": "clxvcrs0000000000000000001"
     *       },
     *       "level": "READ",
     *       "createdAt": "2026-04-25T10:05:00Z"
     *     }
     */
    AccessGrantDto: {
      /** @description Server-generated cuid identifying this grant. */
      id: string;
      /** @description Better Auth user id of the grantee. */
      userId: string;
      target: components['schemas']['GrantTarget'];
      level: components['schemas']['GrantLevel'];
      /**
       * Format: date-time
       * @description ISO-8601 instant when the grant was created.
       */
      createdAt: string;
    };
    /**
     * @description Paginated list of access grants for a given user.
     * @example {
     *       "items": [
     *         {
     *           "id": "clxvgnt0000000000000000001",
     *           "userId": "clxvusr0000000000000000001",
     *           "target": {
     *             "kind": "library",
     *             "libraryId": "clxvp1234567890abcdefghij"
     *           },
     *           "level": "READ",
     *           "createdAt": "2026-04-25T10:00:00Z"
     *         },
     *         {
     *           "id": "clxvgnt0000000000000000002",
     *           "userId": "clxvusr0000000000000000001",
     *           "target": {
     *             "kind": "course",
     *             "courseId": "clxvcrs0000000000000000001"
     *           },
     *           "level": "READ",
     *           "createdAt": "2026-04-25T10:05:00Z"
     *         }
     *       ]
     *     }
     */
    AccessGrantListDto: {
      items: components['schemas']['AccessGrantDto'][];
    };
    /**
     * @description Ordered list of courses the requester is in the middle of, most-recently- watched first. Empty array for new users.
     * @example {
     *       "items": [
     *         {
     *           "courseId": "clxvcrs0000000000000000001",
     *           "courseTitle": "Pragmatic Clean Architecture",
     *           "librarySlug": "conference-recordings",
     *           "percent": 15.79,
     *           "lessonsCompleted": 12,
     *           "lessonsTotal": 76,
     *           "lastSeenAt": "2026-04-25T14:32:00Z",
     *           "lastSeenLessonId": "clxvles0000000000000000042"
     *         },
     *         {
     *           "courseId": "clxvcrs0000000000000000002",
     *           "courseTitle": "Domain-Driven Design by Eric Evans",
     *           "percent": 33.33,
     *           "lessonsCompleted": 6,
     *           "lessonsTotal": 18,
     *           "lastSeenAt": "2026-04-24T10:10:00Z",
     *           "lastSeenLessonId": "clxvles0000000000000000007"
     *         }
     *       ]
     *     }
     */
    ContinueWatchingDto: {
      items: components['schemas']['ContinueWatchingItem'][];
    };
    /**
     * @description A single entry in the continue-watching row, sourced from the `CourseProgressReadModel` projection.
     * @example {
     *       "courseId": "clxvcrs0000000000000000001",
     *       "courseTitle": "Pragmatic Clean Architecture",
     *       "librarySlug": "conference-recordings",
     *       "percent": 15.79,
     *       "lessonsCompleted": 12,
     *       "lessonsTotal": 76,
     *       "lastSeenAt": "2026-04-25T14:32:00Z",
     *       "lastSeenLessonId": "clxvles0000000000000000042"
     *     }
     */
    ContinueWatchingItem: {
      /** @description Server-generated cuid identifying the course. */
      courseId: string;
      /** @description Display title of the course. */
      courseTitle: string;
      /** @description Slug of the parent library, included for the URL builder. Optional because not every layout exposes a per-library slug yet. */
      librarySlug?: string;
      /** @description Course completion = `lessonsCompleted / lessonsTotal * 100`. */
      percent: number;
      /** @description Number of lessons the user has completed in this course. */
      lessonsCompleted: number;
      /** @description Total number of lessons in the course. */
      lessonsTotal: number;
      /**
       * Format: date-time
       * @description Most recent moment any lesson in this course was watched (completed or not).
       */
      lastSeenAt: string;
      /** @description The lesson the player last reported a position on, used to wire the 'Resume' CTA. */
      lastSeenLessonId: string;
    };
    /**
     * @description Full representation of a Course aggregate.
     * @example {
     *       "id": "clxvcrs0000000000000000001",
     *       "libraryId": "clxvp1234567890abcdefghij",
     *       "slug": "pragmatic-clean-architecture",
     *       "title": "Pragmatic Clean Architecture",
     *       "description": "Milan Jovanović's deep-dive into Clean Architecture with .NET.",
     *       "sections": [
     *         {
     *           "id": "clxvsec0000000000000000001",
     *           "position": 1,
     *           "title": "Introduction"
     *         },
     *         {
     *           "id": "clxvsec0000000000000000002",
     *           "position": 2,
     *           "title": "Domain Layer"
     *         }
     *       ],
     *       "progress": {
     *         "percent": 0,
     *         "lessonsCompleted": 0,
     *         "lessonsTotal": 24
     *       },
     *       "createdAt": "2026-04-25T09:00:00Z",
     *       "updatedAt": "2026-04-25T09:00:00Z"
     *     }
     */
    CourseDto: {
      /** @description Server-generated cuid identifying this course. */
      id: string;
      /** @description cuid of the library this course belongs to. */
      libraryId: string;
      slug: components['schemas']['CourseSlug'];
      title: string;
      description?: string;
      /** @description Sections sorted ascending by position. */
      sections: components['schemas']['SectionDto'][];
      progress: components['schemas']['CourseProgress'];
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    /**
     * @description List of courses visible to the requester.
     * @example {
     *       "items": [
     *         {
     *           "id": "clxvcrs0000000000000000001",
     *           "libraryId": "clxvp1234567890abcdefghij",
     *           "slug": "pragmatic-clean-architecture",
     *           "title": "Pragmatic Clean Architecture",
     *           "description": "Milan Jovanović's deep-dive into Clean Architecture with .NET.",
     *           "sections": [
     *             {
     *               "id": "clxvsec0000000000000000001",
     *               "position": 1,
     *               "title": "Introduction"
     *             },
     *             {
     *               "id": "clxvsec0000000000000000002",
     *               "position": 2,
     *               "title": "Domain Layer"
     *             }
     *           ],
     *           "progress": {
     *             "percent": 0,
     *             "lessonsCompleted": 0,
     *             "lessonsTotal": 24
     *           },
     *           "createdAt": "2026-04-25T09:00:00Z",
     *           "updatedAt": "2026-04-25T09:00:00Z"
     *         },
     *         {
     *           "id": "clxvcrs0000000000000000002",
     *           "libraryId": "clxvp1234567890abcdefghij",
     *           "slug": "ddd-by-eric-evans",
     *           "title": "Domain-Driven Design by Eric Evans",
     *           "sections": [
     *             {
     *               "id": "clxvsec0000000000000000003",
     *               "position": 1,
     *               "title": "Putting the Domain Model to Work"
     *             },
     *             {
     *               "id": "clxvsec0000000000000000004",
     *               "position": 2,
     *               "title": "Building Blocks of a Model-Driven Design"
     *             }
     *           ],
     *           "progress": {
     *             "percent": 0,
     *             "lessonsCompleted": 0,
     *             "lessonsTotal": 18
     *           },
     *           "createdAt": "2026-04-25T09:05:00Z",
     *           "updatedAt": "2026-04-25T09:05:00Z"
     *         }
     *       ]
     *     }
     */
    CourseListDto: {
      items: components['schemas']['CourseDto'][];
    };
    /**
     * @description Progress summary for a course from the requester's perspective.
     * @example {
     *       "percent": 0,
     *       "lessonsCompleted": 0,
     *       "lessonsTotal": 24
     *     }
     */
    CourseProgress: {
      /** @description Completion percent. v1 always returns 0 — populated once the LessonProgress projector lands (E10-F01-S01). */
      percent: number;
      lessonsCompleted: number;
      lessonsTotal: number;
    };
    /**
     * @description URL-safe slug. 1–100 chars, lowercase ASCII letters, digits, and hyphens; cannot start or end with a hyphen. Unique within a library.
     * @example pragmatic-clean-architecture
     */
    CourseSlug: string;
    /** @enum {string|null} */
    DependencyStatus: 'ok' | 'degraded' | 'down' | null;
    /**
     * @description Access level. v1 only issues READ; the enum is open for future levels (e.g. ADMIN, NONE for explicit denials).
     * @enum {string}
     */
    GrantLevel: 'READ';
    /** @description The resource to which access is granted. Discriminated by `kind`. */
    GrantTarget:
      | {
          /**
           * @description Discriminator value indicating a library-scoped grant.
           * @enum {string}
           */
          kind: 'library';
          /** @description Server-generated cuid of the target library. */
          libraryId: string;
        }
      | {
          /**
           * @description Discriminator value indicating a course-scoped grant. Accepted in v1 even though the Course aggregate (E06-F03-S01) has not landed yet — keeps the contract stable for E14-F04-S01.
           * @enum {string}
           */
          kind: 'course';
          /** @description Server-generated cuid of the target course (e.g. "DDD by Eric Evans"). */
          courseId: string;
        };
    HealthStatus: {
      status: components['schemas']['DependencyStatus'];
      /** @description Semantic version of the running backend build */
      version: string | null;
      /** @description Seconds since the backend process started */
      uptimeSeconds: number;
      dependencies: {
        db: components['schemas']['DependencyStatus'];
        redis: components['schemas']['DependencyStatus'];
        centrifugo: components['schemas']['DependencyStatus'];
      };
    };
    /**
     * @example {
     *       "id": "clxvp1234567890abcdefghij",
     *       "name": "Conference Recordings",
     *       "rootPath": "/srv/courses/conference",
     *       "createdAt": "2026-04-25T09:00:00Z",
     *       "updatedAt": "2026-04-25T09:00:00Z"
     *     }
     */
    LibraryDto: {
      /** @description Server-generated identifier. */
      id: string;
      /** @description Human-readable label. */
      name: string;
      /** @description Absolute filesystem path to the library root. Must start with `/` (POSIX) or `[A-Za-z]:\` (Windows). */
      rootPath: string;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    /**
     * @example {
     *       "items": [
     *         {
     *           "id": "clxvp1234567890abcdefghij",
     *           "name": "Conference Recordings",
     *           "rootPath": "/srv/courses/conference",
     *           "createdAt": "2026-04-25T09:00:00Z",
     *           "updatedAt": "2026-04-25T09:00:00Z"
     *         },
     *         {
     *           "id": "clxvp0987654321zyxwvutsrq",
     *           "name": "Tutorial Screencasts",
     *           "rootPath": "/srv/courses/tutorials",
     *           "createdAt": "2026-04-20T14:30:00Z",
     *           "updatedAt": "2026-04-22T11:00:00Z"
     *         }
     *       ]
     *     }
     */
    LibraryListDto: {
      items: components['schemas']['LibraryDto'][];
    };
    /**
     * @description Full representation of a Lesson aggregate, including sidecar materials and subtitle tracks.
     * @example {
     *       "id": "clxvles0000000000000000001",
     *       "courseId": "clxvcrs0000000000000000001",
     *       "sectionId": "clxvsec0000000000000000002",
     *       "position": 3,
     *       "title": "Aggregates",
     *       "durationSeconds": 2847,
     *       "materials": [
     *         {
     *           "id": "clxvmat0000000000000000001",
     *           "kind": "doc",
     *           "label": "03 - Aggregates slides",
     *           "sizeBytes": 204800
     *         }
     *       ],
     *       "subtitles": [
     *         {
     *           "id": "clxvsub0000000000000000001",
     *           "language": "en",
     *           "label": "English"
     *         }
     *       ],
     *       "progress": {
     *         "percent": 0,
     *         "completed": false,
     *         "lastSeenAtSeconds": 0
     *       }
     *     }
     */
    LessonDto: {
      /** @description Server-generated cuid identifying this lesson. */
      id: string;
      /** @description cuid of the course this lesson belongs to. */
      courseId: string;
      /** @description cuid of the section this lesson belongs to. */
      sectionId: string;
      /** @description 1-based position within the section. */
      position: number;
      title: string;
      /** @description Video duration in seconds. Populated by E06-F02-S02 (ffprobe). `undefined` until then. */
      durationSeconds?: number;
      /** @description Sidecar materials (PDF / Markdown / text / image). Empty array when none. */
      materials: components['schemas']['MaterialDto'][];
      /** @description Available subtitle tracks. Empty array when none. */
      subtitles: components['schemas']['SubtitleDto'][];
      progress: components['schemas']['LessonProgress'];
    };
    /**
     * @description Per-lesson playback progress for the requesting user.
     * @example {
     *       "percent": 0,
     *       "completed": false,
     *       "lastSeenAtSeconds": 0
     *     }
     */
    LessonProgress: {
      /** @description Completion percent. v1 always returns 0 — populated once the LessonProgress projector lands (E10-F01-S01). */
      percent: number;
      /** @description Whether the lesson is marked as completed. */
      completed: boolean;
      /** @description Last reported watched position in seconds. v1 always returns 0 — populated by the LessonProgress projector (E10-F01-S01). */
      lastSeenAtSeconds: number;
    };
    /**
     * @description Per-user progress state for a single lesson, as persisted after a merge.
     * @example {
     *       "lessonId": "clxvles0000000000000000001",
     *       "positionSeconds": 1080,
     *       "durationSeconds": 1800,
     *       "percent": 60,
     *       "completed": false,
     *       "lastSeenAt": "2026-04-25T14:32:00Z"
     *     }
     */
    LessonProgressDto: {
      /** @description Server-generated cuid identifying the lesson. */
      lessonId: string;
      /** @description Last recorded watch position in seconds. */
      positionSeconds: number;
      /** @description Lesson video duration in seconds. */
      durationSeconds: number;
      /** @description Computed as `positionSeconds / durationSeconds * 100`. Clamped to 100 when position >= duration. */
      percent: number;
      /** @description True once the user crosses the 90 % threshold; never flips back to false. */
      completed: boolean;
      /**
       * Format: date-time
       * @description ISO-8601 instant of the last accepted progress write.
       */
      lastSeenAt: string;
      /**
       * Format: date-time
       * @description Set the first time `completed` flips to true. Stable across subsequent writes. Absent when `completed` is false.
       */
      completedAt?: string;
    };
    /**
     * @description A sidecar material attached to a lesson.
     * @example {
     *       "id": "clxvmat0000000000000000001",
     *       "kind": "doc",
     *       "label": "03 - Aggregates slides",
     *       "sizeBytes": 204800
     *     }
     */
    MaterialDto: {
      /** @description Server-generated cuid identifying this material. */
      id: string;
      kind: components['schemas']['MaterialKind'];
      /** @description Human-readable name derived from the original filename (extension stripped, ordinal prefix preserved if present). */
      label: string;
      /** @description File size in bytes. */
      sizeBytes: number;
    };
    /**
     * @description Coarse classification of a sidecar material. `doc` is `.pdf`, `note` is `.md` / `.txt`, `image` is `.png` / `.jpg`, `slide` is reserved for future use.
     * @example doc
     * @enum {string}
     */
    MaterialKind: 'doc' | 'note' | 'image' | 'slide';
    /** @description RFC 9457 problem details */
    Problem: {
      /**
       * Format: uri
       * @default about:blank
       */
      type: string | null;
      title: string | null;
      /** Format: int32 */
      status: number;
      detail?: string | null;
      instance?: string | null;
      code?: string | null;
    };
    RealtimeToken: {
      /** @description Short-lived HMAC-signed JWT for Centrifugo */
      token: string | null;
      /**
       * Format: date-time
       * @description ISO-8601 instant when the token expires
       */
      expiresAt: string | null;
    };
    /**
     * @description Payload for upserting the requester's progress on a lesson.
     * @example {
     *       "lessonId": "clxvles0000000000000000001",
     *       "positionSeconds": 1080,
     *       "durationSeconds": 1800,
     *       "clientUpdatedAt": "2026-04-25T14:32:00Z"
     *     }
     */
    RecordProgressRequest: {
      /** @description Server-generated cuid identifying the lesson. */
      lessonId: string;
      /** @description Last reported watch position in seconds. Clamped server-side to `[0, durationSeconds]`. */
      positionSeconds: number;
      /** @description Lesson video duration in seconds. Clients pass the player's `duration` from the `loadedmetadata` event; it must match the server-side value once E06-F02-S02 (ffprobe) lands. v1 trusts the client value. */
      durationSeconds: number;
      /**
       * Format: date-time
       * @description ISO-8601 timestamp the client recorded the position. Out-of-order writes (older than the current `lastSeenAt`) are silently accepted and the response echoes the unchanged state.
       */
      clientUpdatedAt: string;
    };
    /**
     * @description Payload for issuing a new access grant.
     * @example {
     *       "userId": "clxvusr0000000000000000001",
     *       "target": {
     *         "kind": "library",
     *         "libraryId": "clxvp1234567890abcdefghij"
     *       },
     *       "level": "READ"
     *     }
     */
    RegisterGrantRequest: {
      /** @description Better Auth user id of the grantee. */
      userId: string;
      target: components['schemas']['GrantTarget'];
      level: components['schemas']['GrantLevel'];
    };
    /**
     * @example {
     *       "name": "Conference Recordings",
     *       "rootPath": "/srv/courses/conference"
     *     }
     */
    RegisterLibraryRequest: {
      /** @description Human-readable label. */
      name: string;
      /** @description Absolute filesystem path to the library root. Accepts POSIX paths starting with `/` or Windows drive paths starting with `[A-Za-z]:\`. Trailing slashes are allowed. */
      rootPath: string;
    };
    /**
     * @description A scan record for a library, produced by the Scan aggregate.
     * @example {
     *       "id": "clxvscn0000000000000000001",
     *       "libraryId": "clxvp1234567890abcdefghij",
     *       "status": "succeeded",
     *       "startedAt": "2026-04-25T10:30:00Z",
     *       "finishedAt": "2026-04-25T10:31:42Z",
     *       "filesScanned": 314,
     *       "filesAdded": 12,
     *       "filesUpdated": 3,
     *       "coursesDiscovered": 7,
     *       "errors": [
     *         {
     *           "path": "02 - Patterns/05 - Repositories.mp4",
     *           "message": "File is not readable — permission denied.",
     *           "code": "unreadable-file"
     *         },
     *         {
     *           "path": "04 - Bounded Contexts/course.json",
     *           "message": "JSON schema validation failed: missing required field 'title'.",
     *           "code": "course-json-invalid"
     *         }
     *       ]
     *     }
     */
    ScanDto: {
      /** @description Server-generated cuid identifying this scan. */
      id: string;
      /** @description cuid of the library that was scanned. */
      libraryId: string;
      status: components['schemas']['ScanStatus'];
      /**
       * Format: date-time
       * @description ISO-8601 instant when the scan was started.
       */
      startedAt: string;
      /**
       * Format: date-time
       * @description Set on terminal status (`succeeded` / `failed` / `cancelled`). Absent while `status: running`.
       */
      finishedAt?: string;
      /** @description Total number of filesystem entries inspected. */
      filesScanned: number;
      /** @description Files that did not exist in the catalog before this scan. */
      filesAdded: number;
      /** @description Files whose metadata changed since the last scan. */
      filesUpdated: number;
      /** @description Course roots detected during this scan. */
      coursesDiscovered: number;
      /** @description Non-fatal per-file errors encountered during the scan. */
      errors: components['schemas']['ScanError'][];
    };
    /**
     * @description A non-fatal error encountered while processing a single file during a scan.
     * @example {
     *       "path": "02 - Patterns/05 - Repositories.mp4",
     *       "message": "File is not readable — permission denied.",
     *       "code": "unreadable-file"
     *     }
     */
    ScanError: {
      /** @description Filesystem path relative to the library root, e.g. `01 - Intro to DDD/03 - Aggregates.mp4`. */
      path: string;
      /** @description Human-readable description of what went wrong. */
      message: string;
      /** @description Machine-readable error key (e.g. `course-json-invalid`, `unreadable-file`, `unsupported-extension`). */
      code?: string;
    };
    /**
     * @description Scan lifecycle. `cancelled` is reserved for v2 admin-cancel; v1 scans only ever transition `running → {succeeded, failed}`.
     * @enum {string}
     */
    ScanStatus: 'running' | 'succeeded' | 'failed' | 'cancelled';
    /**
     * @description Short-lived signed URL for streaming a lesson video.
     * @example {
     *       "url": "http://localhost:3000/api/v1/stream/lessons/clxvles0000000000000000001?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbHh2dXNyMDAwMDAwMDAwMDAwMDAwMDAxIiwibGVzc29uSWQiOiJjbHh2bGVzMDAwMDAwMDAwMDAwMDAwMDAxIiwiZXhwIjoxNzQ1NTc0NDAwfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c",
     *       "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbHh2dXNyMDAwMDAwMDAwMDAwMDAwMDAxIiwibGVzc29uSWQiOiJjbHh2bGVzMDAwMDAwMDAwMDAwMDAwMDAxIiwiZXhwIjoxNzQ1NTc0NDAwfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c",
     *       "expiresAt": "2026-04-25T10:15:00Z"
     *     }
     */
    StreamUrlDto: {
      /**
       * Format: uri
       * @description Full URL the player should request. Carries the signed token as the `token` query parameter so existing video-element implementations work without an Authorization header.
       */
      url: string;
      /** @description Opaque signed token. Format is internal to the backend (currently a JWT-like compact form `header.payload.signature`); clients must round-trip it untouched. */
      token: string;
      /**
       * Format: date-time
       * @description ISO-8601 timestamp at which the token + URL stop being accepted. Clients should request a fresh URL before this moment.
       */
      expiresAt: string;
    };
    /**
     * @description A subtitle track available for a lesson.
     * @example {
     *       "id": "clxvsub0000000000000000001",
     *       "language": "en",
     *       "label": "English"
     *     }
     */
    SubtitleDto: {
      /** @description Server-generated cuid identifying this subtitle track. */
      id: string;
      /** @description BCP-47-ish language code parsed from the filename suffix (`Lesson.en.srt` → `en`). `und` when no suffix is present. */
      language: string;
      /** @description Human-readable label for the subtitle track (e.g. "English"). */
      label: string;
    };
    /**
     * @description A section within a course.
     * @example {
     *       "id": "clxvsec0000000000000000001",
     *       "position": 1,
     *       "title": "Introduction"
     *     }
     */
    SectionDto: {
      /** @description Server-generated cuid identifying this section. */
      id: string;
      /** @description 1-based position within the course. Sections are returned sorted by position. */
      position: number;
      title: string;
    };
    /**
     * @description Payload for updating course metadata. All fields are optional, but at
     *     least one of `title`, `description`, or `slug` must be present
     *     (server-side validation rule — OpenAPI does not have a native
     *     "at-least-one" constraint).
     * @example {
     *       "title": "Pragmatic Clean Architecture (2nd ed.)",
     *       "slug": "pragmatic-clean-architecture-2nd-ed"
     *     }
     */
    UpdateCourseRequest: {
      title?: string;
      description?: string;
      slug?: components['schemas']['CourseSlug'];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  listGrantsByUser: {
    parameters: {
      query: {
        /** @description Better Auth user id whose grants should be returned. */
        userId: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Grant list returned */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AccessGrantListDto'];
        };
      };
      /** @description userId query parameter is missing or empty */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description Missing or invalid bearer token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description Caller does not have the admin role */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
  registerGrant: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RegisterGrantRequest'];
      };
    };
    responses: {
      /** @description Grant created */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AccessGrantDto'];
        };
      };
      /** @description Validation error — missing or malformed fields */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description Missing or invalid bearer token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description Caller does not have the admin role */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description Target library or course not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description A grant for this (userId, target) pair already exists */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
  revokeGrant: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Server-generated cuid identifying the grant to revoke. */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Grant revoked — no body */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Missing or invalid bearer token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description Caller does not have the admin role */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description Grant not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
  listCourses: {
    parameters: {
      query?: {
        /** @description Filter to a single library; omit for everything visible. */
        libraryId?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Course list returned */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CourseListDto'];
        };
      };
      /** @description Missing or invalid bearer token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
  getCourse: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Server-generated cuid identifying the course. */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Course found */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CourseDto'];
        };
      };
      /** @description Missing or invalid bearer token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description Caller does not have a READ grant for the course's library */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description Course not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
  updateCourse: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Server-generated cuid identifying the course to update. */
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateCourseRequest'];
      };
    };
    responses: {
      /** @description Course updated */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CourseDto'];
        };
      };
      /** @description Validation error — malformed fields or no fields provided */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description Missing or invalid bearer token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description Caller does not have the admin role */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description Course not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description A course with the same slug already exists in this library */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
  getContinueWatching: {
    parameters: {
      query?: {
        /** @description How many items the home row needs. */
        limit?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Continue-watching list returned */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ContinueWatchingDto'];
        };
      };
      /** @description Missing or invalid bearer token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
  getLesson: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Server-generated cuid identifying the lesson. */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Lesson found */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LessonDto'];
        };
      };
      /** @description Missing or invalid bearer token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description Requester has no READ grant covering the parent library or course */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description Lesson not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
  issueStreamUrl: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Server-generated cuid identifying the lesson. */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Signed stream URL issued */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['StreamUrlDto'];
        };
      };
      /** @description Missing or invalid bearer token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description Requester has no READ grant on the parent library or course */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description Lesson not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
  listLibraries: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Library list returned */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LibraryListDto'];
        };
      };
      /** @description Missing or invalid bearer token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
  registerLibrary: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RegisterLibraryRequest'];
      };
    };
    responses: {
      /** @description Library registered successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LibraryDto'];
        };
      };
      /** @description Validation error — missing or malformed fields */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description Missing or invalid bearer token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description Caller does not have the Owner-Admin role */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description A library with the same rootPath already exists */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
  getLibrary: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Server-generated cuid identifying the library. */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Library found */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LibraryDto'];
        };
      };
      /** @description Missing or invalid bearer token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description Caller does not have access to this library */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description Library not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
  runLibraryScan: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Server-generated cuid identifying the library to scan. */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Scan accepted and running */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ScanDto'];
        };
      };
      /** @description Missing or invalid bearer token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description Caller does not have the admin role */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description Library not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description A scan is already running for this library */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
  getLatestLibraryScan: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Server-generated cuid identifying the library. */
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Latest scan returned */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ScanDto'];
        };
      };
      /** @description Missing or invalid bearer token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description Caller does not have the admin role */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description Library not found or no scan has been run yet */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
  getHealth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Service and all dependencies are operational */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthStatus'];
        };
      };
      /** @description One or more dependencies are degraded or down */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HealthStatus'];
        };
      };
    };
  };
  recordLessonProgress: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['RecordProgressRequest'];
      };
    };
    responses: {
      /** @description Post-merge progress state returned */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LessonProgressDto'];
        };
      };
      /** @description Validation error — missing or malformed fields */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description Missing or invalid bearer token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description Requester has no READ grant covering the parent library or course */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description Lesson not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
  getLessonProgress: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Server-generated cuid identifying the lesson. */
        lessonId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Progress record returned */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LessonProgressDto'];
        };
      };
      /** @description Missing or invalid bearer token */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description No READ grant — also covers "lesson missing + no grant" to avoid leaking existence */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
      /** @description Lesson exists but the requester has not yet recorded any progress */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
  issueRealtimeToken: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Token issued */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['RealtimeToken'];
        };
      };
      /** @description No active session */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/problem+json': components['schemas']['Problem'];
        };
      };
    };
  };
}
