import tailwindcss from '@tailwindcss/vite';

export default defineNuxtConfig({
  compatibilityDate: '2026-04-18',
  srcDir: 'app/',
  ssr: false,
  // devtools is disabled in dev because vite-plugin-inspect (its hard
  // dependency) interferes with plugin ordering for @intlify/unplugin-vue-i18n
  // — it lets vite:json run after the unplugin's transform of locale JSON
  // files, which then fails because the unplugin has already converted the
  // JSON to a JS module. Re-enable per-developer if needed.
  devtools: { enabled: false },
  modules: ['@nuxt/ui', '@pinia/nuxt', '@nuxtjs/i18n'],

  nitro: {
    // No explicit `preset: 'static'`. With `ssr: false` Nuxt infers the static
    // preset automatically on `nuxt generate`, and forcing it here triggers
    // Nitro's "Payload extraction is recommended" warning that cannot be
    // silenced by user config — `@nuxt/schema` hard-resolves
    // `experimental.payloadExtraction` to `false` whenever `ssr: false`,
    // which the same module then flags as a missing opt-in. Upstream bug.
    //
    // Separately, Nuxt 4.4 + Nitro 2.13 ship overlapping `useAppConfig`
    // auto-imports (`nitropack/runtime/internal/config` +
    // `@nuxt/nitro-server/.../app-config`). Unimport logs a benign
    // "Duplicated imports" warning; @nuxt/nitro-server's copy wins.
    // Pending https://github.com/nuxt/nuxt — expected to clear in 4.5.
  },

  // Translation messages live in `i18n/locales/{en,ru}.json` (the source of
  // truth). They're loaded via `i18n.config.ts` as plain JSON imports rather
  // than @nuxtjs/i18n's `langDir`+`file` mechanism — that mechanism races with
  // Vite's built-in `vite:json` plugin (the unplugin's `include` doesn't
  // reliably match the absolute path Vite passes during transform, and
  // vite:json wins the chain). The vueI18n config approach skips that race:
  // the JSON imports go through Vite's normal module graph and `vite:json`
  // happily parses valid JSON.
  i18n: {
    vueI18n: './i18n.config.ts',
    strategy: 'no_prefix',
    defaultLocale: 'en',
    locales: [
      { code: 'en', language: 'en-US', name: 'English' },
      { code: 'ru', language: 'ru-RU', name: 'Русский' },
    ],
    detectBrowserLanguage: {
      useCookie: true,
      cookieKey: 'i18n_locale',
      redirectOn: 'root',
    },
  },

  // Inject a tiny config script BEFORE the bundle so the runtime-config
  // plugin can read host-set env values (apiBaseUrl, authBaseUrl) without
  // needing to rebuild the SPA per deployment domain. The static file is
  // generated by `apps/web/docker-entrypoint.sh` at container start; in
  // dev it's a 404 (the plugin defaults silently).
  app: {
    head: {
      script: [{ src: '/_app-config.js' }],
    },
  },

  css: ['~/assets/css/main.css'],

  vite: {
    plugins: [tailwindcss()],
    // Pre-bundle libs Vite would otherwise discover at runtime and trigger
    // a full dev-server reload for.
    optimizeDeps: {
      include: ['better-auth/vue'],
    },
  },

  typescript: {
    strict: true,
    typeCheck: false,
  },

  runtimeConfig: {
    public: {
      apiBaseUrl: process.env.NUXT_PUBLIC_API_BASE_URL ?? 'http://localhost:3000/api/v1',
      authBaseUrl: process.env.NUXT_PUBLIC_AUTH_BASE_URL ?? 'http://localhost:3000',
      centrifugoUrl:
        process.env.NUXT_PUBLIC_CENTRIFUGO_URL ?? 'ws://localhost:8000/connection/websocket',
    },
  },

  colorMode: {
    preference: 'dark',
    fallback: 'dark',
  },

  ui: {
    colorMode: true,
  },

  devServer: {
    port: 3001,
    host: '0.0.0.0',
  },
});
