/** @type {import('@commitlint/types').UserConfig} */
export default {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'scope-enum': [
      2,
      'always',
      [
        'root',
        'specs',
        'api-client-ts',
        'api-client-dart',
        'ui',
        'ui_flutter',
        'storybook',
        'backend',
        'web',
        'mobile',
        'docker',
        'ci',
        'github',
        'husky',
        'e2e',
        'claude',
        'deps',
        'tasks',
        'roadmap',
        'plans',
        'security',
      ],
    ],
    'subject-case': [2, 'never', ['upper-case']],
    'body-max-line-length': [1, 'always', 120],
  },
};
