/**
 * AsyncAPI → TypeScript codegen for the realtime client.
 *
 * Reads `asyncapi/centrifugo.yaml`, extracts the payload schemas referenced
 * by each channel, and emits `packages/api-client-ts/src/realtime/channels.ts`
 * containing:
 *   - One interface per payload (generated via json-schema-to-typescript).
 *   - A `RealtimeChannel` union of every channel `address` (with `{param}`
 *     placeholders preserved).
 *   - A `RealtimeChannelPayload<Channel>` conditional type that maps a
 *     channel template to its payload interface.
 *
 * The output is a single deterministic file so the `codegen-drift` CI job
 * catches unreviewed changes.
 */

import { readFileSync, mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { compile } from 'json-schema-to-typescript';
import YAML from 'yaml';

const here = path.dirname(fileURLToPath(import.meta.url));
const specsRoot = path.resolve(here, '..');
const packagesRoot = path.resolve(specsRoot, '..');

const input = path.join(specsRoot, 'asyncapi/centrifugo.yaml');
const outDir = path.join(packagesRoot, 'api-client-ts/src/realtime');
const outFile = path.join(outDir, 'channels.ts');

interface AsyncApiDoc {
  channels: Record<
    string,
    {
      address: string;
      messages: Record<string, { $ref: string }>;
    }
  >;
  components: {
    messages: Record<string, { payload: { $ref: string } }>;
    schemas: Record<string, unknown>;
  };
}

const doc = YAML.parse(readFileSync(input, 'utf8')) as AsyncApiDoc;

function resolveRef(ref: string): { name: string; value: unknown } {
  // Only supports intra-document refs: `#/components/schemas/Foo` or
  // `#/components/messages/Foo`.
  const parts = ref.replace(/^#\//, '').split('/');
  let node: unknown = doc;
  for (const p of parts) {
    node = (node as Record<string, unknown>)[p];
  }
  return { name: parts.at(-1) ?? '', value: node };
}

/**
 * Walk a schema tree and replace every intra-document `$ref` with the
 * dereferenced value. Required because we hand sub-schemas to
 * `json-schema-to-typescript` standalone — its bundled ref-parser tries to
 * resolve `#/components/...` against the sub-schema root, which has no
 * `components` key, and throws `MissingPointerError`.
 *
 * Assumes the schema graph is acyclic (true for our AsyncAPI document — no
 * recursive types). If recursion is ever introduced, swap to a visited-set
 * keyed by `$ref`.
 */
function inlineRefs(node: unknown): unknown {
  if (Array.isArray(node)) return node.map((entry) => inlineRefs(entry));
  if (node !== null && typeof node === 'object') {
    const obj = node as Record<string, unknown>;
    if (typeof obj['$ref'] === 'string') {
      return inlineRefs(resolveRef(obj['$ref']).value);
    }
    const out: Record<string, unknown> = {};
    for (const [k, v] of Object.entries(obj)) {
      out[k] = inlineRefs(v);
    }
    return out;
  }
  return node;
}

interface ChannelEntry {
  address: string;
  payloadName: string;
}

const channels: ChannelEntry[] = [];
const payloadSchemas = new Map<string, unknown>();

for (const channel of Object.values(doc.channels)) {
  const firstMessage = Object.values(channel.messages)[0];
  if (!firstMessage) continue;
  const message = resolveRef(firstMessage.$ref).value as { payload: { $ref: string } };
  const payloadRef = resolveRef(message.payload.$ref);
  const schemaName = payloadRef.name;
  payloadSchemas.set(schemaName, inlineRefs(payloadRef.value));
  channels.push({ address: channel.address, payloadName: schemaName });
}

const banner = `/* eslint-disable */
// ─────────────────────────────────────────────────────────────────────────────
// Generated by \`pnpm --filter @app/specs codegen\` from
// \`packages/specs/asyncapi/centrifugo.yaml\`. DO NOT EDIT BY HAND — your
// changes will be overwritten on next codegen. Edit the AsyncAPI document
// instead.
// ─────────────────────────────────────────────────────────────────────────────
`;

const compiled: string[] = [];
for (const [name, schema] of payloadSchemas) {
  const ts = await compile(schema as Parameters<typeof compile>[0], name, {
    bannerComment: '',
    additionalProperties: false,
    style: { singleQuote: true },
  });
  compiled.push(ts.trim());
}

const channelUnion = channels.map((c) => `  | '${c.address}'`).join('\n');
const payloadMapEntries = channels.map((c) => `  '${c.address}': ${c.payloadName};`).join('\n');

const body = `
export type RealtimeChannel =
${channelUnion};

export interface RealtimeChannelPayloadMap {
${payloadMapEntries}
}

export type RealtimeChannelPayload<C extends RealtimeChannel> =
  RealtimeChannelPayloadMap[C];
`;

mkdirSync(outDir, { recursive: true });
writeFileSync(outFile, `${banner}\n${compiled.join('\n\n')}\n${body}`, 'utf8');

console.warn(`✓ asyncapi codegen → ${path.relative(packagesRoot, outFile)}`);
