import { test, expect } from '@playwright/test';

/**
 * Foundations design-system page coverage.
 *
 * Split into two assertions:
 *
 *   1. **Structural** — every section heading mounts. Runs everywhere
 *      (darwin, linux, CI) and is the canonical smoke for `/dev/foundations`.
 *
 *   2. **Visual regression** — full-page pixel snapshot at 1440x900,
 *      gated behind `process.env.CI`. Snapshots drift heavily between
 *      darwin and linux (font metrics + native form-control rendering),
 *      so the visual test is intentionally CI-only with a Linux
 *      baseline; running it locally on darwin caused false-positive
 *      pixel mismatches and was net-negative for the suite. The Linux
 *      baseline is committed as
 *      `tests/e2e/foundations.spec.ts-snapshots/foundations-chromium-linux.png`
 *      and is regenerated by the next CI run (Playwright writes missing
 *      snapshots on first encounter).
 */
test.use({ viewport: { width: 1440, height: 900 } });

const SECTION_HEADINGS = [
  'Color',
  'Typography',
  'Spacing',
  'Radius',
  'Motion',
  'Buttons',
  'Inputs',
  'Cards',
  'List rows',
  'Tabs',
  'Feedback',
  'Overlays',
  'Progress',
  'Empty States',
  'Loading Skeleton',
  'Avatar',
  'Tag / Chip',
];

test('foundations page renders all sections', async ({ page }) => {
  await page.goto('/dev/foundations');

  await page.waitForSelector('.page-foundations__title', { timeout: 10_000 });

  for (const heading of SECTION_HEADINGS) {
    await expect(
      page.locator('.page-foundations__section-title', { hasText: heading }).first(),
    ).toBeVisible({ timeout: 5_000 });
  }
});

test('foundations visual regression', async ({ page }) => {
  test.skip(
    !process.env.CI,
    'visual regression is CI-only — darwin vs linux font/rendering drift makes the snapshot useless locally',
  );

  await page.goto('/dev/foundations');
  await page.waitForSelector('.page-foundations__title', { timeout: 10_000 });

  for (const heading of SECTION_HEADINGS) {
    await expect(
      page.locator('.page-foundations__section-title', { hasText: heading }).first(),
    ).toBeVisible({ timeout: 5_000 });
  }

  // Allow CSS animations (the AppSkeleton pulse, the spinner, etc.) to settle
  // visually — running animations are clamped to their first frame by
  // Playwright's `animations: 'disabled'` option, but waiting one extra paint
  // catches any lingering layout shift.
  await page.waitForTimeout(200);

  await expect(page).toHaveScreenshot('foundations.png', {
    maxDiffPixelRatio: 0.02,
    fullPage: true,
    animations: 'disabled',
  });
});
