name: app_mobile
description: "Local first coursera"
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.44.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  get_it: ^9.2.1
  intl: any
  dio: ^5.7.0
  flutter_secure_storage: ^10.0.0
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  cupertino_icons: ^1.0.8
  slang: ^4.1.0
  slang_flutter: ^4.1.0
  uuid: ^4.5.1
  firebase_core: ^4.7.0
  firebase_messaging: ^16.2.0
  sentry_flutter: ^8.14.0
  app_ui:
    path: ../../packages/ui_flutter
  app_api_client:
    path: ../../packages/api-client-dart

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.13
  freezed: ^3.0.0
  json_serializable: ^6.8.0
  slang_build_runner: ^4.1.0
  bloc_test: ^10.0.0
  mocktail: ^1.0.4
  built_collection: ">=5.1.1 <6.0.0"
  source_gen: ">=4.0.0 <5.0.0"

flutter:
  uses-material-design: true
