/* eslint-disable */
// ─────────────────────────────────────────────────────────────────────────────
// Generated by `pnpm --filter @app/specs codegen` from
// `packages/specs/asyncapi/centrifugo.yaml`. DO NOT EDIT BY HAND — your
// changes will be overwritten on next codegen. Edit the AsyncAPI document
// instead.
// ─────────────────────────────────────────────────────────────────────────────

export interface HealthUpdate {
  status: 'ok' | 'degraded' | 'down';
  changedAt: string;
  reason?: string;
}

/**
 * Discriminated union of scan events. The `kind` field identifies the
 * concrete type: `progress`, `lesson-discovered`, or `finished`.
 *
 */
export type ScanEvent =
  | {
      kind: 'progress';
      /**
       * cuid
       */
      scanId: string;
      /**
       * cuid
       */
      libraryId: string;
      at: string;
      /**
       * Relative path of the file being processed right now.
       */
      currentPath: string;
      /**
       * Lessons discovered so far in this scan.
       */
      lessonsSoFar: number;
    }
  | {
      kind: 'lesson-discovered';
      scanId: string;
      libraryId: string;
      at: string;
      lessonRelativePath: string;
      sectionTitle: string;
    }
  | {
      kind: 'finished';
      scanId: string;
      libraryId: string;
      at: string;
      /**
       * Terminal status of a library scan.
       */
      status: 'succeeded' | 'failed' | 'partial';
      lessonsTotal: number;
      errorsTotal: number;
    };

export interface NoteUpdated {
  /**
   * cuid
   */
  lessonId: string;
  /**
   * Better Auth user id (UUID v4)
   */
  userId: string;
  updatedAt: string;
  /**
   * Full Markdown body after the edit. Sent in full (not as a diff)
   * because notes are short and the network overhead is dwarfed by
   * the simplicity of last-write-wins reconciliation.
   *
   */
  body: string;
}

export interface ProgressUpdated {
  userId: string;
  lessonId: string;
  positionSeconds: number;
  durationSeconds: number;
  percent: number;
  completed: boolean;
  lastSeenAt: string;
  /**
   * Set when `completed` is true (>= 90% threshold crossed).
   */
  completedAt?: string;
}

/**
 * Discriminated union of every per-user job lifecycle event delivered
 * on `scans:user:{userId}`. The `kind` field identifies the concrete
 * type: a scan publishes `started`, throttled `progress` (no more
 * than ~1 per second per scan), and a final `finished`; a
 * transcription run publishes the same three-phase shape prefixed
 * `transcription-` instead, because it is a second, longer-running
 * job kind fanned out on the same per-user channel rather than a
 * variant of a scan. A receiver must not assume the union is closed
 * at three kinds — treat any `kind` you do not handle as belonging to
 * a job kind you do not render, not as the terminal event.
 *
 */
export type ScanLifecycleEvent =
  | {
      kind: 'started';
      scanId: string;
      libraryId: string;
      libraryName: string;
      at: string;
      /**
       * cuid of the course this scan was scoped to. Absent for a library-wide scan.
       */
      scopeCourseId?: string;
      /**
       * Title of the scoped course. Absent for a library-wide scan.
       */
      scopeCourseName?: string;
    }
  | {
      kind: 'progress';
      scanId: string;
      libraryId: string;
      libraryName: string;
      at: string;
      filesScanned: number;
      filesAdded: number;
      coursesDiscovered: number;
      errorsCount: number;
      /**
       * cuid of the course this scan was scoped to. Absent for a library-wide scan.
       */
      scopeCourseId?: string;
      /**
       * Title of the scoped course. Absent for a library-wide scan.
       */
      scopeCourseName?: string;
    }
  | {
      kind: 'finished';
      scanId: string;
      libraryId: string;
      libraryName: string;
      at: string;
      /**
       * Terminal status of a library scan.
       */
      status: 'succeeded' | 'failed' | 'partial';
      filesScanned: number;
      filesAdded: number;
      coursesDiscovered: number;
      errorsCount: number;
      /**
       * cuid of the course this scan was scoped to. Absent for a library-wide scan.
       */
      scopeCourseId?: string;
      /**
       * Title of the scoped course. Absent for a library-wide scan.
       */
      scopeCourseName?: string;
    }
  | {
      kind: 'transcription-started';
      /**
       * cuid
       */
      transcriptionId: string;
      libraryId: string;
      libraryName: string;
      at: string;
      /**
       * Lessons this run will consider, known up front.
       */
      lessonsTotal: number;
      /**
       * cuid of the course this run was scoped to. Absent for a library-wide run.
       */
      scopeCourseId?: string;
      /**
       * Title of the scoped course. Absent for a library-wide run.
       */
      scopeCourseName?: string;
    }
  | {
      kind: 'transcription-progress';
      transcriptionId: string;
      libraryId: string;
      libraryName: string;
      at: string;
      lessonsTotal: number;
      lessonsSkipped: number;
      lessonsTranscribed: number;
      lessonsFailed: number;
      /**
       * cuid of the course this run was scoped to. Absent for a library-wide run.
       */
      scopeCourseId?: string;
      /**
       * Title of the scoped course. Absent for a library-wide run.
       */
      scopeCourseName?: string;
    }
  | {
      kind: 'transcription-finished';
      transcriptionId: string;
      libraryId: string;
      libraryName: string;
      at: string;
      /**
       * Terminal status of a transcription run, as carried by `transcription-finished`. Mirrors the OpenAPI `TranscriptionStatus` enum minus `running` — a finished event is by definition no longer running.
       */
      status: 'succeeded' | 'failed' | 'cancelled';
      lessonsTotal: number;
      lessonsSkipped: number;
      lessonsTranscribed: number;
      lessonsFailed: number;
      /**
       * cuid of the course this run was scoped to. Absent for a library-wide run.
       */
      scopeCourseId?: string;
      /**
       * Title of the scoped course. Absent for a library-wide run.
       */
      scopeCourseName?: string;
    };

/**
 * Emitted once when the backfill job begins.
 */
export interface BackfillStarted {
  /**
   * Unique cuid identifying the backfill job.
   */
  jobId: string;
  /**
   * ISO-8601 instant when the job started.
   */
  startedAt: string;
  /**
   * Number of libraries included in this backfill run.
   */
  librariesScanned: number;
}

export type RealtimeChannel =
  | 'system:health'
  | 'library:scan:{libraryId}'
  | 'notes:lesson:{lessonId}'
  | 'progress:user:{userId}'
  | 'scans:user:{userId}'
  | 'maintenance:backfill:{jobId}';

export interface RealtimeChannelPayloadMap {
  'system:health': HealthUpdate;
  'library:scan:{libraryId}': ScanEvent;
  'notes:lesson:{lessonId}': NoteUpdated;
  'progress:user:{userId}': ProgressUpdated;
  'scans:user:{userId}': ScanLifecycleEvent;
  'maintenance:backfill:{jobId}': BackfillStarted;
}

export type RealtimeChannelPayload<C extends RealtimeChannel> = RealtimeChannelPayloadMap[C];
